name: Manual push to central

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true
        type: string

jobs:
  push-to-manen-central:
    uses: spring-io/spring-github-workflows/.github/workflows/spring-artifactory-promote-central.yml@main
    with:
      buildName: ${{ inputs.buildName }}
      buildNumber: ${{ inputs.buildNumber }}
    secrets:
      JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      OSSRH_URL: ${{ secrets.OSSRH_URL }}
      OSSRH_S01_TOKEN_USERNAME: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
      OSSRH_S01_TOKEN_PASSWORD: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
      OSSRH_STAGING_PROFILE_NAME: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}